# Generated by Django 2.0.7 on 2018-09-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180909_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Profile')),
                ('cover_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_letters', to='app.Document')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='app.Document')),
            ],
        ),
        migrations.RenameModel(
            old_name='JobStatus',
            new_name='JobType',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='employment_status',
            new_name='job_type',
        ),
        migrations.AlterField(
            model_name='job',
            name='designation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Designation'),
        ),
    ]
