# Generated by Django 2.0.7 on 2018-09-09 21:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180909_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Job'),
        ),
    ]
